#!/bin/bash

currentdir="$(cd "$(dirname "${BASH_SOURCE[0]}")/" >/dev/null 2>&1 && pwd)"

if lsmod|grep nvidia_modeset >/dev/null 2>&1;then
    echo "loading nvidia preferences"
    export __GL_YIELD="NOTHING"
    export __GL_MaxFramesAllowed=1
    export __GL_THREADED_OPTIMIZATIONS=0

    if [ $__GL_THREADED_OPTIMIZATIONS -ne 0 ];then
        if [ $(/sbin/ldconfig -Np|grep libpthread.so.0$ -c) -gt 0 ];then
            LD_PRELOAD+="libpthread.so.0 "
        fi
        if [ $(/sbin/ldconfig -Np|grep libGL.so.1$ -c) -gt 0 ];then
            LD_PRELOAD+="libGL.so.1 "
        fi
    fi

    nvidia-settings -a "[gpu:0]/GPUPowerMizerMode=1" >/dev/null 2>&1&
    nvidia-settings -a OpenGLImageSettings=3 >/dev/null 2>&1&
    nvidia-settings -a SyncToVBlank=0 >/dev/null 2>&1&
    nvidia-settings -a AllowFlipping=1 >/dev/null 2>&1&
else
    export mesa_glthread=false
    export vblank_mode=0 #no vsync
    export LIBGL_DRI3_DISABLE=0
fi
#export SDL_AUDIODRIVER=alsa

#running with kmsdrm
if [ -z "$DISPLAY" ];then
	width=$(fbset |grep --color=never geometry|awk '{print $2}')
	height=$(fbset |grep --color=never geometry|awk '{print $3}')
	extra="+vid_usedesktopres 0 +vid_width $width +vid_height $height +vid_displayfrequency 999 +vid_gamma_workaround 0"
	echo ""
	echo "setting video mode based on current framebuffer resolution, use vid_width/vid_height to customize"
	echo "use s_audiodevicelist list to list devices, set with s_audiodevice X"
	echo ""
fi

olddir=$(pwd)
cd "$currentdir"

nice -n -5 ./ezquake-linux-x86_64 $extra $*

cd "$olddir"
