alias quake="currentdir=$(pwd);cd $HOME/quake;./quake;cd \"$currentdir\""
alias quake-afterquake="currentdir=$(pwd);cd $HOME/quake-afterquake;nice -n -5 ./fteqw64;cd \"$currentdir\""
alias quakepreset="currentdir=$(pwd);cd $HOME/quake;./choose-qw.sh;cd \"$currentdir\""
alias browser="chromium"
alias filebrowser="pcmanfm"
alias update-quake="export DEBIAN_FRONTEND=noninteractive;cd $HOME/build/ezquake-source-official && git reset --hard && git clean -qfdx && git pull && git submodule update --remote --init && eval \$(grep --color=never PKGS_DEB build-linux.sh|head -n1) && echo 'installing deps...' && sudo apt -qqy update;sudo apt -qqy install \$PKGS_DEB && make -j$(nproc);cp ezquake-linux-x86_64 $HOME/quake/. && echo 'copied, update complete.'"
alias nvidia-disable="export DEBIAN_FRONTEND=noninteractive;sudo apt -qqy update;sudo apt -qqy purge '*nvidia*';sudo apt -qqy autopurge"
alias nvidia-enable="export DEBIAN_FRONTEND=noninteractive;sudo apt -qqy update;sudo apt -qqy install libnvidia-glvkspirv libnvidia-glvkspirv nvidia-driver nvidia-smi nvidia-settings nvidia-vulkan-icd nvidia-driver-libs libgles-nvidia1 libgles-nvidia2 nvidia-vulkan-icd;sudo apt -qqy -f install"
alias update-system="sudo apt -qqy update && sudo apt -qqy dist-upgrade"
alias shutdown-system="sudo shutdown -h now"
alias leavemealone="touch $HOME/.leavemealone"

if [ ! -f $HOME/.leavemealone ];then
	echo ""
	echo "quake :"
	echo "run quake (using ezquake, qw compatible): quake"
	echo "change quake (ezquake) assets preset: quakepreset"
	echo "update quake (ezquake) from git: update-quake"
	if [ ! -z "$DISPLAY" ];then
		echo "run afterquake (using fte, qw and netquake compatible): quake-afterquake"
	fi
	echo ""
	#razer mouse functions
	if ls /sys/module/razermouse/drivers/hid:razermouse/*/device_mode > /dev/null 2>&1;then
		echo "razer mouse :"
		echo "set dpi: razer-dpi XXX"
		echo "set polling rate: razer-poll XXX"
		echo ""
	fi
	echo "other :"
	if [ ! -z "$DISPLAY" ];then
		echo "run a web browser: browser"
		echo "run a file browser: filebrowser"
		echo "configure display(s): lxrandr"
		echo "configure networking: connman-gtk (systray icon)"
		echo "disable nvidia driver (use opensource driver nouveau): nvidia-disable"
		echo "enable nvidia driver: nvidia-enable"
	else
		echo "configure networking: connmanctl"
	fi
	echo "update system: update-system"
	echo "shutdown system: shutdown-system"
	echo ""
	echo "to disable these messages: leavemealone"
	echo ""
fi
