#razer mouse functions
if ls /sys/module/razermouse/drivers/hid:razermouse/*/device_mode > /dev/null 2>&1;then
  function razer-dpi(){
    if [ ! -z "$1" ];then
      hex=$(printf "%04x" "$1")
      echo -en "\x${hex:0:2}\x${hex:2:4}"|sudo tee /sys/module/razermouse/drivers/hid:razermouse/*/dpi >/dev/null 2>&1
      if [ $? -ne 0 ];then
        echo "setting dpi failed."
      else
        echo "dpi set to $(cat /sys/module/razermouse/drivers/hid:razermouse/*/dpi)."
        echo "$1" > ${HOME}/.razer_dpi
      fi
    fi
  }
  function razer-rate(){
    if [ ! -z "$1" ];then
      echo -en "$1"|sudo tee /sys/module/razermouse/drivers/hid:razermouse/*/poll_rate >/dev/null
      if [ $? -ne 0 ];then
        echo "setting polling rate failed."
      else
        echo "polling rate set to $(cat /sys/module/razermouse/drivers/hid:razermouse/*/poll_rate)."
        echo "$1" > ${HOME}/.razer_rate
      fi
    fi
  }
  function razer-mode(){
    if [ "$1" = "1" ];then
      echo -n -e "\x03\x00"|sudo tee /sys/module/razermouse/drivers/hid:razermouse/*/device_mode >/dev/null
    else
      echo -n -e "\x00\x00"|sudo tee /sys/module/razermouse/drivers/hid:razermouse/*/device_mode >/dev/null
      echo "$1" > ${HOME}/.razer_mode
    fi
  }
fi

#custom aliases
if [ -e "$HOME/quake-afterquake" ];then
	alias quake-afterquake="currentdir=$(pwd);cd $HOME/quake-afterquake;nice -n -5 ./fteqw64;cd \"$currentdir\""
fi
alias quake-preset="currentdir=$(pwd);cd $HOME/quake;./choose-qw.sh;cd \"$currentdir\""
alias quake-fix="cd $HOME/quake && echo 'lowercasing files and directories...' && find . -depth -exec rename 's/(.*)\/([^\/]*)/$1\/\L$2/' {} \; 2>/dev/null && cd - >/dev/null && echo 'updating quake...' && update-quake && echo 'all done'"
alias browser="chromium"
alias filebrowser="thunar"
alias update-quake="wget -qO /tmp/ezquake-linux https://builds.quakeworld.nu/ezquake/snapshots/latest/linux/x86_64/ezQuake-x86_64.AppImage && mv /tmp/ezquake-linux ${HOME}/quake/ezquake-linux && chmod +x /home/quakeuser/quake/ezquake-linux"
alias nvidia-disable="export DEBIAN_FRONTEND=noninteractive;sudo apt -qqy update;sudo apt -qqy purge '*nvidia*';sudo apt -qqy autopurge"
alias nvidia-enable="export DEBIAN_FRONTEND=noninteractive;sudo apt -qqy update;sudo apt -qqy install nvidia-driver nvidia-settings nvidia-xconfig;sudo apt -qqy -f install"
alias logitech-enable="export DEBIAN_FRONTEND=noninteractive;sudo apt -qqy update;sudo apt -qqy install piper && piper"
alias update-system="sudo apt -qqy update && sudo apt -qqy upgrade"
alias shutdown-system="sudo shutdown -h now"
alias reboot-system="sudo shutdown -r now"
alias leavemealone="touch $HOME/.leavemealone"

function get-nquake() {
	nquakeresourcesurl="https://github.com/nQuake/distfiles/releases/download/snapshot"
	nquakeresourcesurl_backup="https://github.com/ciscon/distfiles/releases/download/snapshot"
	nquakezips="gpl.zip non-gpl.zip"

	echo "updating nquake resources..."
	mkdir -p $HOME/quake/qw.nquake
	mkdir -p /tmp/nquakeresources
	for res in $nquakezips;do
		wget "$nquakeresourcesurl/$res" -O /tmp/nquakeresources/$res || wget "$nquakeresourcesurl_backup/$res" -O /tmp/nquakeresources/$res || echo "failed to download resources" 
		bsdtar xf /tmp/nquakeresources/$res --strip-components=1 -C $HOME/quake/qw.nquake || echo "failed to extract resources"
	done
	rm -rf /tmp/nquakeresources
	echo "switching to nquake preset"
	quake-preset nquake
}
