#!/bin/bash

#stop nodm if we're in the middle of a shutdown
if [[ "$(systemctl is-system-running || true)" == "stopping" ]]; then
	sudo /etc/init.d/nodm stop
fi

#if we build again inside bootable environment, use current hardware for optimizations
export CFLAGS="-march=native -ffast-math -O3 -flto=$(nproc) -pipe"
export LDFLAGS="$CFLAGS"

#start tint first
nice tint2&

#pipewire
pgrep -f pipewire >/dev/null 2>&1 || pipewire&

#connman
(
	pkill -f connman-gtk >/dev/null 2>&1
	while :; do
	nice connman-gtk --tray
	sleep 1
	done
)&

#set background
if [ -f $HOME/background.png ];then
	feh --bg-max $HOME/background.png
fi

#make sure ezquake is registered
xdg-mime default ezQuake.desktop x-scheme-handler/qw >/dev/null 2>&1

fbautostart&
xterm&

exec openbox-session
