#!/bin/bash

#stop nodm if we're in the middle of a shutdown
if [[ "$(systemctl is-system-running || true)" == "stopping" ]]; then
	sudo /etc/init.d/nodm stop
fi

xrdb -load $HOME/.Xresources

export NO_AT_BRIDGE=1

dbus-cleanup-sockets >/dev/null 2>&1
[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && eval $(/usr/bin/dbus-launch --exit-with-session --sh-syntax)
dbus-update-activation-environment --all >/dev/null 2>&1


#if we build again inside bootable environment, use current hardware for optimizations
export CFLAGS="-march=native -O3 -flto=$(nproc) -pipe"
export LDFLAGS="$CFLAGS"

#start tint first
nice tint2&

#pipewire
pgrep -f pipewire >/dev/null 2>&1 || pipewire&

#connman
(
	pkill -f connman-gtk >/dev/null 2>&1
	while :; do
	nice connman-gtk --tray
	sleep 1
	done
)&

#pasystray
(
	pkill -f pasystray >/dev/null 2>&1
	while :; do
	nice pasystray
	sleep 1
	done
)&

(
#overlay background
if [ ! -f "$HOME/background.png" ];then
		convert /background.png -fill grey -pointsize 14 -gravity northwest -annotate +10+10 "$(. /home/quakeuser/.profile_messages)" \
			-fill grey -pointsize 24 -gravity north -annotate +0+5 "build: $(cat /version)" "$HOME/background.png"
fi
#set background
if [ -f "$HOME/background.png" ];then
		feh --bg-max $HOME/background.png
fi
)&

#make sure ezquake is registered
xdg-mime default ezQuake.desktop x-scheme-handler/qw >/dev/null 2>&1

lxpolkit&
fbautostart&
xterm -ls&

for app in $HOME/.config/autostart/*.desktop;do
	dex "$app"&
done

exec openbox-session
