#!/bin/bash

#stop nodm if we're in the middle of a shutdown
if [[ "$(systemctl is-system-running || true)" == "stopping" ]]; then
	sudo /etc/init.d/nodm stop
fi

#if we build again inside bootable environment, use current hardware for optimizations
export CFLAGS="-march=native -flto=$(nproc) -fwhole-program"
export LDFLAGS="$CFLAGS"

#start tint first
tint2&

#set background
if [ -f $HOME/background.png ];then
	feh --bg-max $HOME/background.png
fi

#make sure ezquake is registered
xdg-mime default ezQuake.desktop x-scheme-handler/qw >/dev/null 2>&1

fbautostart&
xterm&

exec openbox-session
