name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        KMSDRM: [0,1]

    steps:
    - uses: actions/checkout@v3
    - name: Read release.md and use it as a body of new release
      id: read_release
      shell: bash
      run: |
        r=$(cat ./release.md)
        r="${r//'%'/'%25'}"
        r="${r//$'\n'/'%0A'}"
        r="${r//$'\r'/'%0D'}"
        echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT
    - name: Install deps
      run: sudo apt-get -qqy update && sudo apt-get -qqy install debootstrap coreutils pigz fdisk kpartx mount uuid-runtime lvm2
    - name: Build
      env:
        KMSDRM: ${{matrix.KMSDRM}}
      run: |
        rm -f ./*.zip
        bash ./create_image.sh
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: ./output/*
        tag: ${{ github.ref }}
        overwrite: true
        body: |
          ${{ steps.read_release.outputs.RELEASE_BODY }}
