name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: sudo apt-get install debootstrap chroot truncate pigz fdisk kpartx losetup uuid-runtime lvm2
    - name: Build
      run: |
        rm -f ./*.zip
        bash ./create_image.sh
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        files: *.zip
        asset_name: quake-bootable
        tag: ${{ github.ref }}
        overwrite: true
