name: Publish

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Publish Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        KMSDRM: [0,1],
        BUILDARCH: ["i386","amd64"]

    steps:
    - uses: actions/checkout@v3
    - name: Read release.md and use it as a body of new release
      id: read_release
      shell: bash
      run: |
        r=$(cat ./release.md)
        r="${r//'%'/'%25'}"
        r="${r//$'\n'/'%0A'}"
        r="${r//$'\r'/'%0D'}"
        echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT
    - name: Install deps
      run: sudo apt-get -qqy update && sudo apt-get -qqy install debootstrap coreutils pigz fdisk kpartx mount uuid-runtime lvm2
    - name: Build
      env:
        KMSDRM: ${{matrix.KMSDRM}}
      run: |
        rm -f ./*.zip
        bash ./create_image.sh
    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: ./output/*
        tag: ${{ steps.bump_version.outputs.new_tag }}
        overwrite: true
        body: |
          ${{ steps.read_release.outputs.RELEASE_BODY }}
